### ISSUE TITLE
Wrong icon size for ITS theme

### ISSUE THREAD

**Issue by TheDude2371** [FlorianWoelki/obsidian-iconize#521]
**Describe the bug**
Icons as part of a link text is huge

**To Reproduce**
1. Create a note. In the directory tree, give it an icon as part of the filename
2. Create a link in another note that references back to that note with the icon. Make sure it has a Header (H1, H2, etc) marking at the start of the line
3. Go to a new line, and when the header and link formatting resolves, the icon itself is massive.

**Expected behavior**
Icon remains the same size as the text in the Header (with link)

**Screenshots**
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/75689309/57873524-8c36-46f5-9196-26bd25bacac0)

**Additional context**
Originally thought to be an issue with link text and the icon. 
Turns out this is any icon that's part of a header, whether part of a link or not.

**Comment by TheDude2371** [comment]
Second screenshot -- here you can see the Source Mode to see hat this has an H2 marking. 
![image](https://github.com/FlorianWoelki/obsidian-iconize/assets/75689309/bba7ed4b-ac94-468f-972c-d72fef3165c6)

Te link marking doesn't seen to enter into the problem at hand.

**Comment by FlorianWoelki** [comment]
Thank you for the report.
What kind of theme do you use?

**Comment by TheDude2371** [comment]
I use ITS for all of my vaults, as it works best for TTRPG, journals, writing, etc with all of its features.

**Comment by Davve37** [comment]
I got the same issue. I am also using the ITS theme.
https://i.imgur.com/RCom8lG.png

**Comment by FlorianWoelki** [comment]
This issue has been resolved in the [latest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.3).

**Comment by Davve37** [comment]
> This issue has been resolved in the [latest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.3).

The icons are still a bit big when appearing in the ITS > [!infobox] callouts. Otherwise it looks good as far as I can tell.

![6CKCW3P](https://github.com/user-attachments/assets/90f6690c-4141-465d-994f-780d950e8e74)

**Comment by FlorianWoelki** [comment]
> > This issue has been resolved in the [latest release](https://github.com/FlorianWoelki/obsidian-iconize/releases/tag/2.14.3).
> 
> 
> 
> The icons are still a bit big when appearing in the ITS > [!infobox] callouts specifically. Otherwise it looks good as far as I can tell. I don't have an issue with icons in a text (as links or plain text) or in the heading of other callout boxes.
> 
> 
> 
> ![6CKCW3P](https://github.com/user-attachments/assets/90f6690c-4141-465d-994f-780d950e8e74)

Thank you for the quick response. I'll take a look at the issue with the callouts!

**Comment by TheDude2371** [comment]
Still showing huge in Headers... not limited to ITS theme, tried in a barebones vault with default theme as well.
![image](https://github.com/user-attachments/assets/f8021f6d-7e13-4bf6-adc0-44b822853f0a)

![image](https://github.com/user-attachments/assets/f5b8f547-546b-41e3-8528-82a4e8740222)

It is pulling the icon as part of a file link, as the file/note does have a link in the manager on the left.
![image](https://github.com/user-attachments/assets/77b7c0e9-ebd1-4c3c-8f07-20a73ba702c5)

**Comment by FlorianWoelki** [comment]
Hmm, for me, it's not behaving like this anymore. I do have the correct size for the headers and titles with any icon.

**Comment by TheDude2371** [comment]
Even if it pulls the icon as part of a file link? 
Obsidian 1.6.7
ITS Theme 1.3
Iconize 2.14.3

Is there anything you could be doing different? I don't want to share this vault as it's chock full of information that I don't want public, it's for my personal use only.
I just checked on both Linux and Windows versions, and behavior is the same.

**Comment by TheDude2371** [comment]
Okay... started a completely fresh vault as a test, and it's working as advertised. Wonder why I'm still getting that behavior. Will look at other plugins/settings.

**Comment by TheDude2371** [comment]
Update... 
Uninstalled/reinstalled Iconize.
Works now. 
Downside is I have to go through everything again to re-add all the file icons. :(

**Comment by FlorianWoelki** [comment]
That's unfortunate, sorry to hear that!
Maybe there was an issue in the `data.json` file of Iconize?
